const cards = [
  { title: "Card One" },
  { title: "Card Two" },
  { title: "Card Three" },
  { title: "Card Four" },
  { title: "Card Five" },
  { title: "Card Six" },
  { title: "Card Seven" },
  { title: "Card Eight" },
  { title: "Card Nine" },
  { title: "Card Ten" },
  { title: "Card Eleven" },
  { title: "Card Twelve" },
  { title: "Card Thirteen" },
  { title: "Card Fourteen" },
  { title: "Card Seventeen" },
  { title: "Card Eighteen" },
  { title: "Card One" },
  { title: "Card Two" },
  { title: "Card Three" },
  { title: "Card Four" },
  { title: "Card Five" },
  { title: "Card Six" },
  { title: "Card Seven" },
  { title: "Card Eight" },
  { title: "Card Nine" },
  { title: "Card Ten" },
  { title: "Card Eleven" },
  { title: "Card Twelve" },
  { title: "Card Thirteen" },
  { title: "Card Fourteen" },
  { title: "Card Seventeen" },
  { title: "Card Eighteen" }
];

export default cards;
